DROP TABLE "COMPETITION";
DROP TABLE "ENTRAINEMENT";
DROP TABLE "UTILISATEUR";

CREATE TABLE "UTILISATEUR" (
    "UserID" varchar(200)   NOT NULL,
    "Nom" varchar(200)   NOT NULL,
    "Prenom" varchar(200)   NOT NULL,
    "Age" int   NOT NULL,
    "Categorie" varchar(200)   NOT NULL,
    CONSTRAINT "pk_UTILISATEUR" PRIMARY KEY (
        "UserID"
     )
);

CREATE TABLE "COMPETITION" (
    "Date" date   NOT NULL,
    "Lieu" varchar(200)   NOT NULL,
    "Type" varchar(20)   NOT NULL,
    "Categorie" varchar(200)   NOT NULL,
    "Coureurs" varchar(200)   NOT NULL,
    "Gagant" varchar(200)   NOT NULL
);

CREATE TABLE "ENTRAINEMENT" (
    "Date" date   NOT NULL,
    "Lieu" varchar(200)   NOT NULL,
    "Type" varchar(20)   NOT NULL,
    "Coureurs" varchar(200)   NOT NULL
);


ALTER TABLE "COMPETITION" ADD CONSTRAINT "fk_COMPETITION_Coureurs" FOREIGN KEY("Coureurs")
REFERENCES "UTILISATEUR" ("UserID");

ALTER TABLE "COMPETITION" ADD CONSTRAINT "fk_COMPETITION_Gagant" FOREIGN KEY("Gagant")
REFERENCES "UTILISATEUR" ("UserID");

ALTER TABLE "ENTRAINEMENT" ADD CONSTRAINT "fk_ENTRAINEMENT_Coureurs" FOREIGN KEY("Coureurs")
REFERENCES "UTILISATEUR" ("UserID");

/*ROLE*/

DROP ROLE ADMIN22_ROLE_ADHERENT;
DROP ROLE ADMIN22_ROLE_ABSTRAIT;
DROP ROLE ADMIN22_ROLE_SECRETAIRE;
DROP ROLE ADMIN22_ROLE_COACH;

CREATE ROLE ADMIN22_ROLE_ADHERENT;
CREATE ROLE ADMIN22_ROLE_ABSTRAIT;
CREATE ROLE ADMIN22_ROLE_SECRETAIRE;
CREATE ROLE ADMIN22_ROLE_COACH;

/*GRANT ROLE ADHERENT*/
GRANT SELECT, UPDATE ON UTILISATEUR TO ADMIN22_ROLE_ADHERENT;
GRANT SELECT ON ENTRAINEMENT TO ADMIN22_ROLE_ADHERENT;
GRANT SELECT ON COMPETITION TO ADMIN22_ROLE_ADHERENT;

/*GRANT ROLE ABSTRAIT*/
GRANT UPDATE ON ENTRAINEMENT TO ADMIN22_ROLE_ABSTRAIT;
GRANT UPDATE ON COMPETITION TO ADMIN22_ROLE_ABSTRAIT;

/*GRANT ROLE SECRETAIRE*/
GRANT DELETE, INSERT ON UTILISATEUR TO ADMIN22_ROLE_SECRETAIRE;
GRANT DELETE, INSERT ON COMPETITION TO ADMIN22_ROLE_SECRETAIRE;

/*GRANT ROLE COACH*/
GRANT DELETE, INSERT ON ENTRAINEMENT TO ADMIN22_ROLE_COACH;


CREATE OR REPLACE PACKAGE set_emp_ctx_pkg IS
PROCEDURE set_emp;
END;
/
CREATE OR REPLACE PACKAGE BODY set_emp_ctx_pkg IS
PROCEDURE set_emp
IS
nom_ctx VARCHAR2(20);
depto_ctx VARCHAR2(20);
BEGIN
nom_ctx:=SYS_CONTEXT('USERENV', 'SESSION_USER');
DBMS_SESSION.SET_CONTEXT('emp_ctx', 'nom', nom_ctx);
SELECT depto INTO DEPTO_CTX
FROM scott.employes
WHERE UPPER(NOM)=nom_ctx;
DBMS_SESSION.SET_CONTEXT('emp_ctx', 'depto', depto_ctx);
END set_emp;
END set_emp_ctx_pkg;
/
