DROP TABLE "COMPETITION";
DROP TABLE "ENTRAINEMENT";
DROP TABLE "UTILISATEUR";

CREATE TABLE "UTILISATEUR" (
    "UserID" varchar(200)   NOT NULL,
    "Nom" varchar(200)   NOT NULL,
    "Prenom" varchar(200)   NOT NULL,
    "Age" int   NOT NULL,
    "Categorie" varchar(200)   NOT NULL,
    CONSTRAINT "pk_UTILISATEUR" PRIMARY KEY (
        "UserID"
     )
);

CREATE TABLE "COMPETITION" (
    "Date" date   NOT NULL,
    "Lieu" varchar(200)   NOT NULL,
    "Type" varchar(20)   NOT NULL,
    "Categorie" varchar(200)   NOT NULL,
    "Coureurs" varchar(200)   NOT NULL,
    "Gagant" varchar(200)   NOT NULL
);

CREATE TABLE "ENTRAINEMENT" (
    "Date" date   NOT NULL,
    "Lieu" varchar(200)   NOT NULL,
    "Type" varchar(20)   NOT NULL,
    "Coureurs" varchar(200)   NOT NULL
);


ALTER TABLE "COMPETITION" ADD CONSTRAINT "fk_COMPETITION_Coureurs" FOREIGN KEY("Coureurs")
REFERENCES "UTILISATEUR" ("UserID");

ALTER TABLE "COMPETITION" ADD CONSTRAINT "fk_COMPETITION_Gagant" FOREIGN KEY("Gagant")
REFERENCES "UTILISATEUR" ("UserID");

ALTER TABLE "ENTRAINEMENT" ADD CONSTRAINT "fk_ENTRAINEMENT_Coureurs" FOREIGN KEY("Coureurs")
REFERENCES "UTILISATEUR" ("UserID");

/*ROLE*/
DROP ROLE ADMIN22_ROLE_PUBLIC;
DROP ROLE ADMIN22_ROLE_ADHERENT;
DROP ROLE ADMIN22_ROLE_ABSTRAIT;
DROP ROLE ADMIN22_ROLE_SECRETAIRE;
DROP ROLE ADMIN22_ROLE_COACH;

CREATE ROLE ADMIN22_ROLE_PUBLIC;
CREATE ROLE ADMIN22_ROLE_ADHERENT;
CREATE ROLE ADMIN22_ROLE_ABSTRAIT;
CREATE ROLE ADMIN22_ROLE_SECRETAIRE;
CREATE ROLE ADMIN22_ROLE_COACH;


/*GRANT ROLE PUBLIC*/
GRANT SELECT ON COMPETITION TO ADMIN22_ROLE_PUBLIC;

/*GRANT ROLE ADHERENT*/
GRANT SELECT, UPDATE ON UTILISATEUR TO ADMIN22_ROLE_ADHERENT;
GRANT SELECT ON ENTRAINEMENT TO ADMIN22_ROLE_ADHERENT;
GRANT ADMIN22_ROLE_PUBLIC TO ADMIN22_ROLE_ADHERENT;

/*GRANT ROLE ABSTRAIT*/
GRANT UPDATE ON ENTRAINEMENT TO ADMIN22_ROLE_ABSTRAIT;
GRANT UPDATE ON COMPETITION TO ADMIN22_ROLE_ABSTRAIT;
GRANT ADMIN22_ROLE_ADHERENT TO ADMIN22_ROLE_ABSTRAIT;

/*GRANT ROLE SECRETAIRE*/
GRANT DELETE, INSERT ON UTILISATEUR TO ADMIN22_ROLE_SECRETAIRE;
GRANT DELETE, INSERT ON COMPETITION TO ADMIN22_ROLE_SECRETAIRE;
GRANT ADMIN22_ROLE_ABSTRAIT TO ADMIN22_ROLE_SECRETAIRE;

/*GRANT ROLE COACH*/
GRANT DELETE, INSERT ON ENTRAINEMENT TO ADMIN22_ROLE_COACH;
GRANT ADMIN22_ROLE_ABSTRAIT TO ADMIN22_ROLE_COACH;

/*Attribution role to USER*/
GRANT ADMIN22_ROLE_ADHERENT TO USER1,USER2;
GRANT ADMIN22_ROLE_COACH TO USER3;
GRANT ADMIN22_ROLE_SECRETAIRE TO USER4;

/*select * from dba_roles where ROLE='ADMIN22_ROLE_ADHERENT';
select * from DBA_ROLE_PRIVS where GRANTEE='USER2' AND GRANTED_ROLE LIKE ('ADMIN22%');
*/

/*Création VPD Restriction select Utilisateur*/
CREATE OR REPLACE CONTEXT is_adherent_ctx  USING is_adherent_pkg;

CREATE OR REPLACE PACKAGE is_adherent_pkg IS
  PROCEDURE is_adherent;
END;
/

CREATE OR REPLACE PACKAGE BODY is_adherent_pkg IS
  PROCEDURE is_adherent_proc
  IS
    UserID_ctx VARCHAR2(20);
  BEGIN
    UserID_ctx:=SYS_CONTEXT('USERENV', 'SESSION_USER');
    DBMS_SESSION.SET_CONTEXT('UserID_ctx', 'UserID', UserID_ctx);
    SELECT UserID_ctx INTO UserID_ctx
    FROM ADMIN22.UTILISATEUR
    WHERE UPPER(NOM)=UserID_ctx;
  END is_adherent_proc;
END is_adherent_pkg;
/
